# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
# edited by Chuizheng Kong 
# on 07/29/2024

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# figure out how to cache the installation of the following packages
# ENV VIRTUAL_ENV=/usr/local
# ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
# RUN /install.sh && rm /install.sh
RUN pip install uv==0.5.1
 
# cache the installation of the following packages
RUN --mount=type=cache,target=/root/.cache \
    uv pip install --system \
        torch \
        torchvision \
        torchaudio \
        "numpy<2.0" \
        opencv-python==4.10.0.84 \
        pandas \
        scipy \
        scikit-learn \
        matplotlib \
        tqdm \
        ipykernel \
        ultralytics \
        plotly \
        roboflow \
        nbformat \
        open3d \
        imutils \
        lapx \
        pyserial \
        sahi 

RUN --mount=type=cache,target=/root/.cache \
    uv pip uninstall --system \
        opencv-python-headless 
